### ISSUE TITLE
Mint 21.1 

### ISSUE THREAD

**Issue by mcibuk** [costales/folder-color#25]
In Mint 21.1, when I want to change the color of a directory other than my home directory, I get a "permission denied" error. For example the "usr" directory. When I commented  line 163 and refreshed manually, it is work. How can I fix this problem. Thanks.

Terminal Output of Error:
Traceback (most recent call last):
  File "/usr/share/caja-python/extensions/folder-color.py", line 335, in _menu_activate_color
    self.foldercolor.set_color(item_path, self._get_skel_folder(item_path, icon)['filename'], True)
  File "/usr/share/caja-python/extensions/folder-color.py", line 114, in set_color
    self.restore_color(item_path)
  File "/usr/share/caja-python/extensions/folder-color.py", line 159, in restore_color
    self._refresh(item_path)
  **File "/usr/share/caja-python/extensions/folder-color.py", line 163, in _refresh
    os.utime(item_path, None)**
PermissionError: [Errno 13] Permission denied

**Comment by costales** [comment]
As you are not the owner, it is not possible
